2022-11-30 11:43:15,572 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,577 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 11:43:15,581 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,584 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,590 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,593 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,598 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,603 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,606 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,609 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function test_password_hashing_is_correct line 50 | 
2022-11-30 11:43:15,612 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,615 |    INFO | server | fnc: is_authorized | args: ({'user': {'username': 'u2', 'password': 'password'}}, {'u2': 'StreamWriter', 'user1': 'StreamWriter'}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function test_user_is_authorized line 74 | 
2022-11-30 11:43:15,615 |    INFO | server | User is already authorized
authorized = {'u2': 'StreamWriter', 'user1': 'StreamWriter'}
2022-11-30 11:43:15,619 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,623 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 11:48:16,456 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-30 11:48:16,460 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 11:48:22,900 |    INFO | server | Connection from ('127.0.0.1', 56968) | waiting authorize
2022-11-30 11:48:22,914 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669798102.900856, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 11:48:22,916 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 11:48:22,918 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 11:48:25,281 |    INFO | server | Client ('127.0.0.1', 56968) wants to quit
2022-11-30 11:48:25,789 |    INFO | server | User "u2" disconnected
2022-11-30 11:48:31,284 | WARNING | server | Server closing
2022-11-30 11:48:46,860 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-30 11:48:46,865 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 11:48:48,662 | WARNING | server | Server closing
2022-11-30 12:03:00,823 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-30 12:03:00,826 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:03:03,558 | WARNING | server | Server closing
2022-11-30 12:04:45,332 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 21 | 
2022-11-30 12:04:45,336 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:04:46,747 | WARNING | server | Server closing
2022-11-30 12:05:39,910 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 18 | 
2022-11-30 12:05:39,915 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:05:45,102 | WARNING | server | Server closing
2022-11-30 12:07:23,343 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 18 | 
2022-11-30 12:07:23,347 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:07:28,595 |    INFO | server | Connection from ('127.0.0.1', 58064) | waiting authorize
2022-11-30 12:07:28,599 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799248.595521, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:07:28,602 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:07:28,604 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:07:41,431 |    INFO | server | Client ('127.0.0.1', 58064) wants to quit
2022-11-30 12:07:41,947 |    INFO | server | User "u2" disconnected
2022-11-30 12:07:49,226 | WARNING | server | Server closing
2022-11-30 12:13:05,671 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 18 | 
2022-11-30 12:13:05,674 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:15:20,287 |    INFO | server | Connection from ('127.0.0.1', 58371) | waiting authorize
2022-11-30 12:15:20,290 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799720.286005, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:15:20,292 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:15:20,294 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:15:29,491 |    INFO | server | Connection from ('127.0.0.1', 58379) | waiting authorize
2022-11-30 12:15:29,493 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799729.490784, 'user': {'password': 'password', 'username': 'u2'}}, {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001AE2378BF70>()]> transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:15:29,493 |    INFO | server | User is already authorized
authorized = {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001AE2378BF70>()]> transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}
2022-11-30 12:15:29,495 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:16:06,043 |    INFO | server | Client ('127.0.0.1', 58371) wants to quit
2022-11-30 12:16:06,556 |    INFO | server | User "u2" disconnected
2022-11-30 12:16:10,776 |    INFO | server | Client ('127.0.0.1', 58379) wants to quit
2022-11-30 12:16:11,291 |    INFO | server | User "u2" disconnected
2022-11-30 12:16:11,291 |   ERROR | server | Server error | u2 ('127.0.0.1', 58379) has already left
2022-11-30 12:17:11,271 |    INFO | server | Connection from ('127.0.0.1', 58461) | waiting authorize
2022-11-30 12:17:11,273 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799831.271336, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:17:11,275 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:17:11,277 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:17:36,394 |    INFO | server | User "u2" disconnected
2022-11-30 12:17:37,778 |    INFO | server | Connection from ('127.0.0.1', 58484) | waiting authorize
2022-11-30 12:17:37,780 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799857.778999, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:17:37,782 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:17:37,783 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:17:54,789 |    INFO | server | Client ('127.0.0.1', 58484) wants to quit
2022-11-30 12:17:55,292 |    INFO | server | User "u2" disconnected
2022-11-30 12:19:28,265 |    INFO | server | Connection from ('127.0.0.1', 58546) | waiting authorize
2022-11-30 12:19:28,267 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799968.265088, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:19:28,269 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:19:28,271 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:19:31,104 |    INFO | server | Client ('127.0.0.1', 58546) wants to quit
2022-11-30 12:19:31,617 |    INFO | server | User "u2" disconnected
2022-11-30 12:19:58,829 |    INFO | server | Connection from ('127.0.0.1', 58578) | waiting authorize
2022-11-30 12:19:58,831 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799998.829102, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:19:58,833 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:19:58,834 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:20:01,391 |    INFO | server | Client ('127.0.0.1', 58578) wants to quit
2022-11-30 12:20:01,898 |    INFO | server | User "u2" disconnected
2022-12-05 14:42:40,675 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:42:40,699 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 14:43:03,930 | WARNING | server | Server closing
2022-12-05 14:47:20,979 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:47:21,004 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 14:47:24,611 |    INFO | server | Connection from ('127.0.0.1', 65412) | waiting authorize
2022-12-05 14:47:24,617 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670240844.611519, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:47:24,619 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:47:24,620 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:49:38,632 | WARNING | server | Server closing
2022-12-05 14:51:40,810 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:53:02,322 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:54:31,582 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:55:40,589 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:55:40,609 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 14:55:46,004 |    INFO | server | Connection from ('127.0.0.1', 1222) | waiting authorize
2022-12-05 14:55:46,008 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241346.004928, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:55:46,009 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:55:46,011 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:56:09,853 |    INFO | server | Client ('127.0.0.1', 1222) wants to quit
2022-12-05 14:56:10,117 |    INFO | server | User "u2" disconnected
2022-12-05 14:56:17,413 |    INFO | server | Connection from ('127.0.0.1', 1239) | waiting authorize
2022-12-05 14:56:17,415 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241377.413395, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:56:17,417 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:56:17,419 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:57:37,754 | WARNING | server | Server closing
2022-12-05 14:57:39,522 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:57:39,542 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 14:57:46,394 |    INFO | server | Connection from ('127.0.0.1', 1295) | waiting authorize
2022-12-05 14:57:46,397 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241466.393858, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:57:46,398 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:57:46,400 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:57:54,656 |    INFO | server | Client ('127.0.0.1', 1295) wants to quit
2022-12-05 14:57:54,915 |    INFO | server | User "u2" disconnected
2022-12-05 14:58:00,560 |    INFO | server | Connection from ('127.0.0.1', 1305) | waiting authorize
2022-12-05 14:58:00,562 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241480.560387, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:58:00,564 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:58:00,565 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:59:14,661 |    INFO | server | Connection from ('127.0.0.1', 1351) | waiting authorize
2022-12-05 14:59:14,663 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241554.661439, 'user': {'password': 'password', 'username': 'u2'}}, {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=448 read=<_OverlappedFuture pending overlapped=<pending, 0x23632652dc0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000023632660460>()]> transport=<_ProactorSocketTransport fd=448 read=<_OverlappedFuture pending overlapped=<pending, 0x23632652dc0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:59:14,664 |    INFO | server | User is already authorized
authorized = {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=448 read=<_OverlappedFuture pending overlapped=<pending, 0x23632652dc0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000023632660460>()]> transport=<_ProactorSocketTransport fd=448 read=<_OverlappedFuture pending overlapped=<pending, 0x23632652dc0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}
2022-12-05 14:59:14,665 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:59:23,051 |    INFO | server | Client ('127.0.0.1', 1351) wants to quit
2022-12-05 14:59:23,304 |    INFO | server | User "u2" disconnected
2022-12-05 14:59:30,305 |    INFO | server | User "u2" disconnected
2022-12-05 14:59:30,305 |   ERROR | server | Server error | u2 ('127.0.0.1', 1305) has already left
2022-12-05 15:01:35,145 | WARNING | server | Server closing
2022-12-05 15:08:01,380 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:08:01,401 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:08:16,799 | WARNING | server | Server closing
2022-12-05 15:09:30,336 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:09:30,357 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:10:25,442 | WARNING | server | Server closing
2022-12-05 15:10:27,310 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:10:27,330 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:12:09,345 | WARNING | server | Server closing
2022-12-05 15:12:10,995 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:12:11,016 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:12:26,330 | WARNING | server | Server closing
2022-12-05 15:15:14,513 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:15:14,541 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:15:21,894 |    INFO | server | Connection from ('127.0.0.1', 1635) | waiting authorize
2022-12-05 15:15:21,897 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242521.888626, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:15:21,899 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:15:21,901 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:15:40,390 | WARNING | server | Server closing
2022-12-05 15:16:13,403 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:16:13,422 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:16:49,609 | WARNING | server | Server closing
2022-12-05 15:16:50,962 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:16:50,983 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:16:54,390 |    INFO | server | Connection from ('127.0.0.1', 1698) | waiting authorize
2022-12-05 15:16:54,393 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242614.383011, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:16:54,395 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:16:54,396 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:17:21,351 | WARNING | server | Server closing
2022-12-05 15:17:23,008 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:17:23,029 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:17:35,056 | WARNING | server | Server closing
2022-12-05 15:17:42,198 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:17:42,219 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:17:44,310 |    INFO | server | Connection from ('127.0.0.1', 1733) | waiting authorize
2022-12-05 15:17:44,314 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242664.303402, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:17:44,315 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:17:44,317 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:18:01,952 | WARNING | server | Server closing
2022-12-05 15:18:03,250 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:18:03,270 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:18:09,004 |    INFO | server | Connection from ('127.0.0.1', 1748) | waiting authorize
2022-12-05 15:18:09,007 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242688.997396, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:18:09,009 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:18:09,010 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:18:44,220 | WARNING | server | Server closing
2022-12-05 15:18:45,899 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:18:45,919 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:18:48,397 |    INFO | server | Connection from ('127.0.0.1', 1782) | waiting authorize
2022-12-05 15:18:48,400 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242728.394001, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:18:48,402 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:18:48,403 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:19:04,991 | WARNING | server | Server closing
2022-12-05 15:19:06,884 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:19:06,904 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:19:10,300 |    INFO | server | Connection from ('127.0.0.1', 1796) | waiting authorize
2022-12-05 15:19:10,303 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242750.297165, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:19:10,305 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:19:10,307 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:19:15,712 |    INFO | server | Client ('127.0.0.1', 1796) wants to quit
2022-12-05 15:19:15,964 |    INFO | server | User "u2" disconnected
2022-12-05 15:19:18,149 | WARNING | server | Server closing
2022-12-05 15:19:28,240 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:19:28,260 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:19:53,105 | WARNING | server | Server closing
2022-12-05 15:20:29,825 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:20:29,849 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:20:31,424 |    INFO | server | Connection from ('127.0.0.1', 1849) | waiting authorize
2022-12-05 15:20:31,427 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242831.421376, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:20:31,428 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:20:31,430 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:20:39,015 |    INFO | server | User "u2" disconnected
2022-12-05 15:20:41,065 | WARNING | server | Server closing
2022-12-05 15:20:42,074 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:20:42,094 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:20:43,211 |    INFO | server | Connection from ('127.0.0.1', 1865) | waiting authorize
2022-12-05 15:20:43,214 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242843.208664, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:20:43,216 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:20:43,218 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:21:41,627 |    INFO | server | User "u2" disconnected
2022-12-05 15:21:43,210 | WARNING | server | Server closing
2022-12-05 15:21:45,687 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:21:45,708 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:21:47,815 |    INFO | server | Connection from ('127.0.0.1', 1912) | waiting authorize
2022-12-05 15:21:47,819 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242907.808296, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:21:47,820 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:21:47,822 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:21:50,188 |    INFO | server | User "u2" disconnected
2022-12-05 15:22:31,162 | WARNING | server | Server closing
2022-12-05 15:22:32,229 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:22:32,251 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:22:34,587 |    INFO | server | Connection from ('127.0.0.1', 1937) | waiting authorize
2022-12-05 15:22:34,590 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242954.584696, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:22:34,592 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:22:34,594 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:22:49,362 | WARNING | server | Server closing
2022-12-05 15:22:53,242 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:22:53,302 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:22:58,715 |    INFO | server | Connection from ('127.0.0.1', 1969) | waiting authorize
2022-12-05 15:22:58,721 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242978.710362, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:22:58,725 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:22:58,728 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:23:20,105 |    INFO | server | Client ('127.0.0.1', 1969) wants to quit
2022-12-05 15:23:20,356 |    INFO | server | User "u2" disconnected
2022-12-05 15:23:30,925 | WARNING | server | Server closing
2022-12-05 15:23:33,987 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:23:34,040 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:25:32,081 | WARNING | server | Server closing
2022-12-05 15:25:42,678 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:25:42,697 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:26:03,315 | WARNING | server | Server closing
2022-12-05 15:26:04,514 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:26:04,542 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:26:05,884 |    INFO | server | Connection from ('127.0.0.1', 2079) | waiting authorize
2022-12-05 15:26:05,887 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243165.881271, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:26:05,889 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:26:05,890 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:26:13,915 | WARNING | server | Server closing
2022-12-05 15:26:15,110 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:26:15,131 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:26:52,966 | WARNING | server | Server closing
2022-12-05 15:26:54,198 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:26:54,218 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:27:28,361 | WARNING | server | Server closing
2022-12-05 15:27:29,301 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:27:29,322 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:27:30,778 |    INFO | server | Connection from ('127.0.0.1', 2138) | waiting authorize
2022-12-05 15:27:30,781 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243250.775881, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:27:30,783 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:27:30,785 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:30:30,081 | WARNING | server | Server closing
2022-12-05 15:30:31,455 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:30:31,486 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:30:33,224 |    INFO | server | Connection from ('127.0.0.1', 2243) | waiting authorize
2022-12-05 15:30:33,227 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243433.22001, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:30:33,229 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:30:33,231 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:30:51,524 | WARNING | server | Server closing
2022-12-05 15:30:52,790 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:30:52,811 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:30:53,861 |    INFO | server | Connection from ('127.0.0.1', 2271) | waiting authorize
2022-12-05 15:30:53,864 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243453.858207, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:30:53,866 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:30:53,867 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:31:19,415 | WARNING | server | Server closing
2022-12-05 15:31:22,067 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:31:22,109 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:32:50,570 | WARNING | server | Server closing
2022-12-05 15:33:15,944 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:33:15,988 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:33:16,704 |    INFO | server | Connection from ('127.0.0.1', 2353) | waiting authorize
2022-12-05 15:33:16,708 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243596.701407, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:33:16,710 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:33:16,711 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:33:25,024 |    INFO | server | Client ('127.0.0.1', 2353) wants to quit
2022-12-05 15:33:25,285 |    INFO | server | User "u2" disconnected
2022-12-05 15:33:26,752 |    INFO | server | Connection from ('127.0.0.1', 2361) | waiting authorize
2022-12-05 15:33:26,754 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243606.750165, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:33:26,756 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:33:26,757 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:33:36,578 | WARNING | server | Server closing
2022-12-05 15:33:37,880 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:33:37,908 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:33:38,167 |    INFO | server | Connection from ('127.0.0.1', 2379) | waiting authorize
2022-12-05 15:33:38,170 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243618.164143, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:33:38,172 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:33:38,174 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:34:07,234 | WARNING | server | Server closing
2022-12-05 15:34:08,619 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:34:08,640 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:34:10,133 |    INFO | server | Connection from ('127.0.0.1', 2397) | waiting authorize
2022-12-05 15:34:10,136 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243650.127309, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:34:10,138 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:34:10,140 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:34:14,448 |    INFO | server | User "u2" disconnected
2022-12-05 15:34:55,669 | WARNING | server | Server closing
2022-12-05 15:35:00,146 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:35:00,166 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:36:08,303 | WARNING | server | Server closing
2022-12-05 15:36:13,138 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:36:13,158 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:37:22,541 | WARNING | server | Server closing
2022-12-05 15:37:23,586 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:37:23,607 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:37:26,082 |    INFO | server | Connection from ('127.0.0.1', 2523) | waiting authorize
2022-12-05 15:37:26,085 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243846.075762, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:37:26,087 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:37:26,089 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:37:29,262 |    INFO | server | User "u2" disconnected
2022-12-05 15:37:30,513 |    INFO | server | Connection from ('127.0.0.1', 2529) | waiting authorize
2022-12-05 15:37:30,515 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243850.506656, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:37:30,517 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:37:30,519 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:38:13,112 |    INFO | server | User "u2" disconnected
2022-12-05 15:38:15,013 |    INFO | server | Connection from ('127.0.0.1', 2569) | waiting authorize
2022-12-05 15:38:15,015 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243895.007702, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:38:15,016 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:38:15,018 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:38:16,258 |    INFO | server | Client ('127.0.0.1', 2569) wants to quit
2022-12-05 15:38:16,518 |    INFO | server | User "u2" disconnected
2022-12-05 15:38:20,289 | WARNING | server | Server closing
2022-12-05 15:39:18,634 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:39:18,659 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:44:37,521 | WARNING | server | Server closing
2022-12-05 15:44:39,429 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:44:39,459 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:45:56,822 | WARNING | server | Server closing
2022-12-05 15:46:29,219 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:46:29,253 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:47:43,234 | WARNING | server | Server closing
2022-12-05 15:47:46,405 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:47:46,440 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:48:34,512 | WARNING | server | Server closing
2022-12-05 15:51:07,497 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:51:07,547 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:51:29,845 | WARNING | server | Server closing
2022-12-05 15:51:37,167 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:51:37,203 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:55:07,540 |    INFO | server | fnc: get_database_object | args: (PosixPath('/mnt/i/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:56:16,901 |    INFO | server | fnc: get_database_object | args: (PosixPath('/mnt/i/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:56:16,993 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:56:19,415 | WARNING | server | Server closing
2022-12-05 15:56:26,306 | WARNING | server | Server closing
2022-12-05 15:56:28,756 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:56:28,797 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:56:50,958 | WARNING | server | Server closing
2022-12-05 15:57:25,337 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:57:25,376 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:57:48,704 | WARNING | server | Server closing
2022-12-05 15:57:49,721 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:57:49,767 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:57:56,693 |    INFO | server | Connection from ('127.0.0.1', 3446) | waiting authorize
2022-12-05 15:57:56,696 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245076.687195, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 15:57:56,697 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 15:57:56,699 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 15:59:04,868 | WARNING | server | Server closing
2022-12-05 15:59:06,041 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:59:06,076 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:59:30,086 |    INFO | server | Connection from ('127.0.0.1', 3524) | waiting authorize
2022-12-05 15:59:30,090 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245170.079151, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 15:59:30,092 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 15:59:30,094 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 15:59:52,557 | WARNING | server | Server closing
2022-12-05 15:59:53,620 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:59:53,655 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:59:55,956 |    INFO | server | Connection from ('127.0.0.1', 12098) | waiting authorize
2022-12-05 15:59:55,959 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245195.950978, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 15:59:55,961 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 15:59:55,962 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:00:24,838 |    INFO | server | User "u2" disconnected
2022-12-05 16:01:20,283 | WARNING | server | Server closing
2022-12-05 16:01:21,438 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:01:21,475 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:01:48,082 | WARNING | server | Server closing
2022-12-05 16:01:48,893 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:01:48,928 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:02:55,955 | WARNING | server | Server closing
2022-12-05 16:02:57,238 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:02:57,276 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:02:59,842 |    INFO | server | Connection from ('127.0.0.1', 12212) | waiting authorize
2022-12-05 16:02:59,846 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245379.836768, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:02:59,848 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:02:59,850 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:03:06,379 |    INFO | server | User "u2" disconnected
2022-12-05 16:03:08,221 |    INFO | server | Connection from ('127.0.0.1', 12220) | waiting authorize
2022-12-05 16:03:08,223 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245388.216102, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:03:08,225 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:03:08,226 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:03:17,992 |    INFO | server | Client ('127.0.0.1', 12220) wants to quit
2022-12-05 16:03:18,250 |    INFO | server | User "u2" disconnected
2022-12-05 16:03:20,827 | WARNING | server | Server closing
2022-12-05 16:04:07,159 |    INFO | server | fnc: get_database_object | args: (PosixPath('/mnt/i/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 16:04:07,212 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:04:26,371 |    INFO | server | Connection from ('127.0.0.1', 39304) | waiting authorize
2022-12-05 16:04:26,383 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245466.356406, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 59 | 
2022-12-05 16:04:26,394 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function verify_password line 139 | 
2022-12-05 16:04:26,400 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 60 | 
2022-12-05 16:04:45,389 |    INFO | server | Client ('127.0.0.1', 39304) wants to quit
2022-12-05 16:04:45,640 |    INFO | server | User "u2" disconnected
2022-12-05 16:04:46,962 |    INFO | server | Connection from ('127.0.0.1', 39306) | waiting authorize
2022-12-05 16:04:46,968 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245486.948171, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 59 | 
2022-12-05 16:04:46,979 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function verify_password line 139 | 
2022-12-05 16:04:46,986 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 60 | 
2022-12-05 16:04:53,721 | WARNING | server | Server closing
2022-12-05 16:10:35,302 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:10:57,902 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:10:57,942 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:11:11,408 |    INFO | server | Connection from ('127.0.0.1', 12508) | waiting authorize
2022-12-05 16:11:11,411 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245871.403694, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:11:11,413 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:11:11,415 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:11:34,894 | WARNING | server | Server closing
2022-12-05 16:13:14,305 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:13:14,344 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:13:16,823 |    INFO | server | Connection from ('127.0.0.1', 12580) | waiting authorize
2022-12-05 16:13:16,827 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245996.822798, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:13:16,828 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:13:16,830 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:14:17,237 | WARNING | server | Server closing
2022-12-05 16:14:21,068 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:14:21,129 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:14:23,426 |    INFO | server | Connection from ('127.0.0.1', 12619) | waiting authorize
2022-12-05 16:14:23,430 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670246063.425157, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:14:23,432 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:14:23,433 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:21:58,144 | WARNING | server | Server closing
2022-12-05 16:22:00,361 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:22:00,401 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:22:03,200 |    INFO | server | Connection from ('127.0.0.1', 13008) | waiting authorize
2022-12-05 16:22:03,204 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670246523.200436, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:22:03,205 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 144 | 
2022-12-05 16:22:03,207 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 58 | 
2022-12-05 16:22:10,088 | WARNING | server | Server closing
2022-12-05 16:27:26,587 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:27:26,625 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:27:29,594 |    INFO | server | Connection from ('127.0.0.1', 13286) | waiting authorize
2022-12-05 16:27:29,597 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670246849.594825, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:27:29,600 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 58 | 
2022-12-05 16:27:32,197 |    INFO | server | Client ('127.0.0.1', 13286) wants to quit
2022-12-05 16:27:32,455 |    INFO | server | User "u2" disconnected
2022-12-05 16:27:32,455 |   ERROR | server | Server error | u2 ('127.0.0.1', 13286) has already left
2022-12-05 16:27:58,527 | WARNING | server | Server closing
2022-12-05 16:28:01,026 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:28:01,062 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:28:03,536 |    INFO | server | Connection from ('127.0.0.1', 13310) | waiting authorize
2022-12-05 16:28:03,539 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670246883.534081, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:28:03,541 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:28:03,542 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 58 | 
2022-12-05 16:28:07,268 |    INFO | server | Client ('127.0.0.1', 13310) wants to quit
2022-12-05 16:28:07,527 |    INFO | server | User "u2" disconnected
2022-12-05 16:28:10,537 | WARNING | server | Server closing
