2022-11-29 15:35:05,572 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 10 | 
2022-11-29 15:40:16,656 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 198 | 
2022-11-29 15:40:16,656 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'alert': 'Well connected'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 199 | 
2022-11-29 15:40:16,657 |    INFO | server | fnc: make_secure_password | args: ('test_password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 200 | 
2022-11-29 15:40:36,659 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 10 | 
2022-11-29 15:50:52,976 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 16 | 
2022-11-29 15:55:03,966 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 12 | 
2022-11-29 15:55:22,660 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 12 | 
2022-11-29 15:56:02,230 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 15:56:14,413 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 15:56:30,158 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 15:57:05,599 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 15:57:28,214 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 15:58:56,140 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 15:59:09,612 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:00:01,588 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:01:22,752 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:02:53,024 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:03:13,327 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:05:27,620 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:06:08,609 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:08:02,835 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:08:54,267 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:10:04,780 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 16 | 
2022-11-29 16:10:11,376 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 16 | 
2022-11-29 16:11:46,302 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 15 | 
2022-11-29 16:12:23,333 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 15 | 
2022-11-29 16:12:28,788 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 15 | 
2022-11-29 16:12:31,370 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669727551.367025, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 65 | 
2022-11-29 16:12:31,372 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 152 | 
2022-11-29 16:12:31,374 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 67 | 
2022-11-29 16:19:26,684 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:20:58,303 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 16:21:42,221 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 16:23:50,009 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 203 | 
2022-11-29 16:23:50,009 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'alert': 'Well connected'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 204 | 
2022-11-29 16:23:50,010 |    INFO | server | fnc: make_secure_password | args: ('test_password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 205 | 
2022-11-29 16:24:02,403 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 204 | 
2022-11-29 16:24:02,404 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'alert': 'Well connected'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 205 | 
2022-11-29 16:24:02,405 |    INFO | server | fnc: make_secure_password | args: ('test_password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 206 | 
2022-11-29 16:24:10,928 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 204 | 
2022-11-29 16:24:10,929 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'alert': 'Well connected'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 205 | 
2022-11-29 16:24:10,930 |    INFO | server | fnc: make_secure_password | args: ('test_password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 206 | 
2022-11-29 16:24:36,077 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 204 | 
2022-11-29 16:24:36,078 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'alert': 'Well connected'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 205 | 
2022-11-29 16:24:36,078 |    INFO | server | fnc: make_secure_password | args: ('test_password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 206 | 
2022-11-29 16:24:48,022 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 204 | 
2022-11-29 16:24:48,023 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'alert': 'Well connected'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 205 | 
2022-11-29 16:24:48,023 |    INFO | server | fnc: make_secure_password | args: ('test_password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 206 | 
2022-11-29 16:25:10,659 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 204 | 
2022-11-29 16:25:10,660 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'alert': 'Well connected'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 205 | 
2022-11-29 16:25:10,660 |    INFO | server | fnc: make_secure_password | args: ('test_password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 206 | 
2022-11-29 16:25:44,715 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 16:26:27,907 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 12 | 
2022-11-29 16:30:46,077 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 14 | 
2022-11-29 16:31:26,545 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 203 | 
2022-11-29 16:31:26,546 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'alert': 'Well connected'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 204 | 
2022-11-29 16:31:26,546 |    INFO | server | fnc: make_secure_password | args: ('test_password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 205 | 
2022-11-29 16:35:39,946 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 12 | 
2022-11-29 16:35:47,001 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669728946.997148, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-11-29 16:35:47,003 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-11-29 16:35:47,004 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-11-29 16:37:25,792 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 16:37:29,951 |    INFO | server | Connection from ('127.0.0.1', 43991) | waiting authorize
2022-11-29 16:37:29,954 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669729049.951835, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-11-29 16:37:29,956 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-11-29 16:37:29,958 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-11-29 16:37:51,682 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 16:38:32,726 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 16:38:35,450 |    INFO | server | Connection from ('127.0.0.1', 44157) | waiting authorize
2022-11-29 16:38:35,454 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669729115.450541, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-11-29 16:38:35,455 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-11-29 16:38:35,457 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-11-29 16:39:12,662 |    INFO | server | User "u2" disconnected
2022-11-29 16:40:51,273 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 16:40:51,276 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-29 16:41:01,733 | WARNING | server | Server closing
2022-11-29 16:43:38,248 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 16:43:38,252 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-29 16:43:47,159 |    INFO | server | Connection from ('127.0.0.1', 44518) | waiting authorize
2022-11-29 16:43:47,162 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669729427.159144, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-11-29 16:43:47,164 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-11-29 16:43:47,166 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-11-29 16:45:48,614 | WARNING | server | Server closing
2022-11-29 16:45:50,212 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-29 16:45:50,216 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-29 16:45:52,519 |    INFO | server | Connection from ('127.0.0.1', 44652) | waiting authorize
2022-11-29 16:45:52,522 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669729552.518108, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-29 16:45:52,524 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 142 | 
2022-11-29 16:45:52,525 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-29 16:46:18,929 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 194 | 
2022-11-29 16:46:18,929 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'alert': 'Well connected'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 195 | 
2022-11-29 16:46:18,930 |    INFO | server | fnc: make_secure_password | args: ('test_password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function <module> line 196 | 
2022-11-29 16:46:40,650 |    INFO | server | User "u2" disconnected
2022-11-29 16:46:50,830 | WARNING | server | Server closing
